name: retro_messenger
description: Retro style OTT messenger inspired by 2014 feature phones.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.15.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^14.6.0
  firebase_auth: ^5.0.0
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.0
  intl: ^0.19.0
  # 선택 암호화 스텁
  cryptography: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/messages_seed.json
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/NotoSansKR-Regular.otf
